import React, {useState} from 'react';
import {ArrowUpRight, ArrowRight, Download, Target} from 'lucide-react';
import {ResponsiveContainer, BarChart, Bar, Cell, LabelList, XAxis, YAxis, CartesianGrid, Tooltip, ReferenceLine, LineChart, Line, Legend} from 'recharts';
import data from './campaign.json';
import {CampaignViewModel} from './models';
import {Card, KPI, download, percent, repo} from './components';

const model = new CampaignViewModel(data);
export default function Management() {
  const [week, setWeek] = useState(data.decision.week);
  const [channelMeasure, setChannelMeasure] = useState('attendees');
  const row = data.weekly.find(item => item.week === week);
  const decision = model.decision(week);
  const channels = [...data.channels].sort((a, b) => b[channelMeasure] - a[channelMeasure]);
  const final = model.final;
  const weeklyTarget = data.targets.weekly;
  const currentMisses = model.missedWeeks.filter(item => item.week <= week);
  const closeoutHeadline = final.cumulative_attendance < data.targets.campaign
    ? 'Close the campaign honestly. The total fell short.'
    : model.missedWeeks.length ? 'The total passed. The weekly promise did not.' : 'Both the weekly and total targets were met.';
  return <>
    <div className="eyebrow">OPERATIONS / EIGHT-WEEK CAMPAIGN</div>
    <div className="page-heading"><div><h1>Turn reach into<br/><em>real attendance.</em></h1><p>{weeklyTarget}+ students each week. {data.targets.campaign}+ attendances. One accountable operating rhythm.</p></div><label className="filter">Review week<select value={week} onChange={event => setWeek(Number(event.target.value))}>{data.weekly.map(item => <option key={item.week} value={item.week}>Week {item.week}</option>)}</select></label></div>
    <div className="notice">{data.mode}. Explore a retrospective scenario, not a live recruitment campaign. The week selector changes the review and forecast; full-campaign charts remain labeled below.</div>
    <div className="kpis">
      <KPI label={`WEEK ${week} · ATTENDANCE`} value={row.attendees} detail={`${row.weekly_goal_met ? '✓ Target met' : '! Below target'} · target ${weeklyTarget}`}/>
      <KPI label="CUMULATIVE ATTENDANCE" value={row.cumulative_attendance} detail={`Through Week ${week} · pace target ${row.cumulative_target}`}/>
      <KPI label="SHOW RATE" value={percent(row.show_rate)} detail={`${row.attendees} attended / ${row.registrations} registered`}/>
      <KPI label="FULL SCENARIO · EIGHT WEEKS" value={`${final.cumulative_attendance} / ${data.targets.campaign}`} detail={`${model.metWeeks} of ${data.weekly.length} weekly targets met · ${model.missedWeeks.length} missed`}/>
    </div>
    <div className="decision" aria-live="polite"><div><span className="eyebrow">WEEK {week} / REVIEW THE RESULT</span><h2>{week === final.week ? closeoutHeadline : row.weekly_goal_met ? 'Protect the next week, not just the total.' : 'A weekly miss needs a response.'}</h2><p>Recorded action: {row.intervention}.</p><p>{currentMisses.length ? `Weekly misses through this point: ${currentMisses.map(item => `Week ${item.week}`).join(', ')}. A later surplus does not erase them.` : 'Every weekly target through this review point was met.'}</p></div><div><b>{row.weekly_goal_met ? '✓ Selected week: target met' : '! Selected week: target missed'}</b><p><strong>Next check</strong><br/>{model.nextCheck(week)}<br/>Accountable owner: Piter.</p></div></div>
    <Card title={`What we could see before Week ${week}`} sub="T−3 forecast uses only earlier weeks and the selected week's registrations/confirmations. It does not use that week's eventual attendance.">
      <div className="forecast-grid"><div><span>Expected attendance</span><strong>{decision.forecast_expected_attendance.toFixed(1)}</strong><small>80% modeled range: {decision.forecast_p10}–{decision.forecast_p90}</small></div><div><span>Chance of {weeklyTarget}+</span><strong>{percent(decision.forecast_probability_at_least_20)}</strong><small>Model estimate, not a guarantee</small></div><div><span>Early-warning status</span><strong className={`risk-${decision.risk_status.toLowerCase()}`}>{decision.risk_status}</strong><small>{decision.risk_status === 'GREEN' ? 'Maintain controls' : 'Intervene before the seminar'}</small></div><div><span>Registration safety target</span><strong>{decision.safety_target_registrations}</strong><small>{row.t3_registrations} registered at T−3</small></div></div>
      <div className="action"><Target size={22}/><div><b>Model-recommended action at T−3</b><p>{decision.recommended_intervention}</p></div></div>
      <p className="muted small">Model status is not an operational sign-off. Piter must separately verify partner commitments, permissions, reminders, and delivery readiness.</p>
      {week === 1 && <p className="muted small">Week 1 has no prior campaign observations; the domain model uses its documented starting assumptions.</p>}
    </Card>
    <div className="two"><Card title="Every week counts" sub="Full eight-week scenario. Select a bar to review that week; the target applies to every week.">
      <ResponsiveContainer width="100%" height={290}><BarChart data={data.weekly} margin={{top: 24, right: 20, bottom: 4, left: -12}}><CartesianGrid vertical={false} stroke="#e6ecee"/><XAxis dataKey="week" tickFormatter={value => `W${value}`}/><YAxis allowDecimals={false}/><Tooltip labelFormatter={value => `Week ${value}`}/><ReferenceLine y={weeklyTarget} stroke="#b75a36" strokeDasharray="5 5"/><Bar isAnimationActive={false} dataKey="attendees" name="Actual attendance" radius={[6, 6, 0, 0]} onClick={entry => setWeek(entry.week)} cursor="pointer"><LabelList dataKey="attendees" position="top"/>{data.weekly.map(item => <Cell key={item.week} fill={!item.weekly_goal_met ? '#b85a36' : model.recoveredWeeks.includes(item) ? '#22566c' : '#26877f'} stroke={item.week === week ? '#173a42' : 'none'} strokeWidth={3}/>)}</Bar></BarChart></ResponsiveContainer>
      <div className="chart-legend"><span>Dashed line · target {weeklyTarget}</span><span>! W{model.missedWeeks[0]?.week} · missed</span><span>↗ W{model.recoveredWeeks[0]?.week} · recovered</span></div>
      <details className="chart-data"><summary>Read exact weekly values</summary><table><thead><tr><th>Week</th><th>Attended</th><th>Target</th><th>Result</th></tr></thead><tbody>{data.weekly.map(item => <tr key={item.week}><td>{item.week}</td><td>{item.attendees}</td><td>{weeklyTarget}</td><td>{item.weekly_goal_met ? 'Met' : 'Missed'}</td></tr>)}</tbody></table></details>
    </Card><Card title="A pace we can sustain" sub="Full eight-week trajectory. These are seminar attendances, not unique students."><ResponsiveContainer width="100%" height={290}><LineChart data={data.weekly} margin={{top: 15, right: 20, bottom: 4, left: -10}}><CartesianGrid vertical={false} stroke="#e6ecee"/><XAxis dataKey="week" tickFormatter={value => `W${value}`}/><YAxis/><Tooltip/><Legend/><Line isAnimationActive={false} type="monotone" dataKey="cumulative_attendance" name="Actual" stroke="#26877f" strokeWidth={3}/><Line isAnimationActive={false} dataKey="cumulative_target" name="Target pace" stroke="#71858d" strokeDasharray="5 5"/></LineChart></ResponsiveContainer><p className="chart-note">{final.cumulative_attendance - data.targets.campaign} above the total target; {model.missedWeeks.length} weekly target still missed.</p></Card></div>
    <Card title="The recovery playbook, in action" sub={`Fixed Week ${data.decision.week} case study · compare the T−3 risk signal with the modeled partner + confirmation intervention.`}>
      <div className="recovery">{data.recovery.map((item, index) => <React.Fragment key={item.Scenario}>{index === 1 && <ArrowRight className="recovery-arrow"/>}<div className={index ? 'recovery-good' : 'recovery-risk'}><span>{index ? 'AFTER PLANNED INTERVENTION' : 'BEFORE INTERVENTION'}</span><strong>{item['Expected attendance']}<small>expected attendees</small></strong><b>{percent(item['P(attendance ≥20)'])} chance of {weeklyTarget}+</b><p>{item.Risk} — {index ? 'On track in the model' : 'Action required'}</p><small>{item.Registrations} registrations · {item.Confirmations} confirmations</small></div></React.Fragment>)}</div>
      <div className="action"><Target size={22}/><div><b>Same model. A specific intervention.</b><p>{data.decision.recommended_intervention} The modeled improvement is not a causal guarantee. Actual attendance recorded for Week {data.decision.week}: {data.decision.weekly_attendance}.</p></div></div>
    </Card>
    <div className="two"><Card title="Grow beyond one network" sub="Full-campaign channel contribution. Compare reach outcomes with effort efficiency."><label className="inline-filter">Compare by<select value={channelMeasure} onChange={event => setChannelMeasure(event.target.value)}><option value="attendees">Actual attendees</option><option value="attendees_per_effort">Attendees per effort unit</option></select></label><ResponsiveContainer width="100%" height={310}><BarChart data={channels} layout="vertical" margin={{left: 4, right: 28}}><XAxis type="number"/><YAxis dataKey="channel" type="category" width={126}/><Tooltip formatter={value => Number(value).toFixed(channelMeasure === 'attendees' ? 0 : 2)}/><Bar isAnimationActive={false} dataKey={channelMeasure} name={channelMeasure === 'attendees' ? 'Attendees' : 'Attendees per effort unit'} fill="#26877f" radius={[0, 5, 5, 0]}/></BarChart></ResponsiveContainer><p className="small muted">Effort units are sample planning units, not dollars or verified staff hours.</p></Card>
    <Card title="Free learning → downstream value" sub="Full-campaign opt-in pathway. The seminar stays free; a conversion is not verified revenue."><div className="funnel">{data.funnel.map(item => <div key={item.Stage}><div><span>{item.Stage}</span><b>{item['Synthetic count']}</b></div><div className="track"><div style={{width: `${item['Synthetic count'] / data.funnel[0]['Synthetic count'] * 100}%`}}/></div><small>{item['Business purpose']}</small></div>)}</div><p className="small muted">Any offering, price, compensation, and attribution rules require SaNDAI's agreement. This model does not invent them.</p></Card></div>
    <Card title="Ownership is a rhythm" sub="Repeatable gates. One accountable owner. The prototype recommends; it does not send reminders or run outreach."><p><strong>Accountable owner — Piter Garcia.</strong> Owns the eight-week objective, cadence, measurement, escalation, decisions, and reporting.</p><p><strong>Collaborative execution.</strong> Approved work can involve SaNDAI, faculty, career services, academic departments, student organizations, community/partner organizations, and assigned team members. Every delegated action has an owner, deadline, expected output, and follow-up. Piter tracks results and triggers the next action when performance falls short.</p><p><strong>Piter owns the result; collaborators help execute the system.</strong></p><div className="cadence">{data.cadence.map(item => <div key={item.Gate}><b>{item.Gate}</b><p>{item['Required action']}</p><small>{item.Owner}</small></div>)}</div></Card>
    <details className="card"><summary>Inspect the evidence, data and technical companion</summary><p>Calculated directly by CampaignMonitor and DecisionEngine, the same Python objects used in the notebooks. The website uses only the committed sample data; it does not write to the shared operational data plane.</p><div className="resource-actions"><a href={`${repo}/blob/main/START-HERE.md`} target="_blank" rel="noreferrer">Review strategy, notebooks and source <ArrowUpRight size={15}/></a><button className="secondary" onClick={() => download('sandai-campaign.json', JSON.stringify(data, null, 2), 'application/json')}><Download size={16}/>Download sample results</button></div></details>
  </>;
}
